car_collection/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from car_collection.models import User, db
from car_collection.forms import UserLoginForm

from werkzeug.security import check_password_hash, generate_password_hash

from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    userform = UserLoginForm()

    try:
        if request.method == 'POST' and userform.validate_on_submit():
            email = userform.email.data
            password = userform.password.data
            print(email,password)

            user = User(email = email, password = password)
            print(user)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check your form')
    return render_template('signup.html', form=userform)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    userform = UserLoginForm()

    try:
    # if True:
        if request.method == "POST" and userform.validate_on_submit():
            email = userform.email.data
            password = userform.password.data
            # print(email, password)
            # print('testing')

            logged_user = User.query.filter_by(email = email).first()
            print(logged_user)
            print(check_password_hash(logged_user.password, password))
            print(logged_user.password)
            print(generate_password_hash(password))
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                print('You are successfully logged in via: Email/Password', 'auth.success')
                return redirect(url_for('site.profile'))
            else:
                print('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=userform)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

car_collection/site/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from car_collection.forms import CarForm
from flask_login import login_required, current_user
from car_collection.models import Car, CarSchema, db


site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')
    

@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    carform = CarForm()

    try:
        if request.method == 'POST' and carform.validate_on_submit():
            make = carform.make.data
            model = carform.model.data
            year = carform.year.data
            color = carform.color.data
            description = carform.description.data
            price = carform.price.data
            miles_per_gallon = carform.miles_per_gallon.data
            max_speed = carform.max_speed.data
            seats = carform.seats.data
            user_token = current_user.token

            car = Car(make, model, year, color, description, price, miles_per_gallon,
                      max_speed, seats, user_token)
            
            db.session.add(car)
            db.session.commit()

            return redirect(url_for('site.profile'))
        
    except:
        raise Exception('Drone not created, please check your form and try again.')
    user_token = current_user.token
    cars = Car.query.filter_by(user_token=user_token)

    return render_template('profile.html', form=carform, cars=cars)



   

car_collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Collection API</title>
</head>
<body>

    <nav class="ct-nav">
        <div>
            <img src="../static/images/9479.png" alt="Cars Logo" id="car-nav-bar">
        </div>

        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>My Car Collection</li>
                </a>
                <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('site.profile')}}">
                        <li>Profile</li>
                    </a>
                    <a href="{{ url_for('auth.logout')}}">
                        <li>Log Out</li>
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                {% endif %}
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

car_collection/templates/carform.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
    <fieldset class="'make-field">
        {{ form.make.label }}
        {{ form.make(class='form-control', placeholder='Name') }}
    </fieldset>
    <fieldset class="'model-field">
        {{ form.model.label }}
        {{ form.model(class='form-control', placeholder='Model') }}
    </fieldset>
    <fieldset class="'year-field">
        {{ form.year.label }}
        {{ form.year(class='form-control', placeholder='Year') }}
    </fieldset>
    <fieldset class="'color-field">
        {{ form.color.label }}
        {{ form.color(class='form-control', placeholder='Color') }}
    </fieldset>
    <fieldset class="'description-field">
        {{ form.description.label }}
        {{ form.description(class='form-control', placeholder='Description') }}
    </fieldset>
    <fieldset class="'price-field">
        {{ form.price.label }}
        {{ form.price(class='form-control', placeholder='Price') }}
    </fieldset>
    <fieldset class="'mpg-field">
        {{ form.miles_per_gallon.label }}
        {{ form.miles_per_gallon(class='form-control', placeholder='Miles Per Gallon') }}
    </fieldset>
    <fieldset class="'speed-field">
        {{ form.max_speed.label }}
        {{ form.max_speed(class='form-control', placeholder='max_speed') }}
    </fieldset>
    <fieldset class="'seats-field">
        {{ form.seats.label }}
        {{ form.seats(class='form-control', placeholder='Seats') }}
    </fieldset>

    {{ form.submit_button(class='btn btn-primary btn-block mt-2')}}

</div>
</form>

car_collection/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>